#pragma once
#include <gtest/gtest.h>
#include <glad/glad.h>
#include <string>
#include <functional> 
#include <Windows.h>
#include "Common.h"
#include "ShaderProgram.h"
#include "../../HiveFX/RenderEnv.h"